name: Build and Deploy Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout code
       run: actions/checkhout@v3

      -name:Build Docker image
       run: docker build -t app .

       -name: Run Docker Container 
        run: docker run app
        
